/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsDate,
  MaxLength,
  IsOptional,
  IsEnum,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { EnumAssetsTypeField } from "./EnumAssetsTypeField";
import { EnumAssetsStatus } from "./EnumAssetsStatus";
import { Assignments } from "../../assignments/base/Assignments";
import { Departments } from "../../departments/base/Departments";

@ObjectType()
class Assets {
  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description!: string | null;

  @ApiProperty({
    required: false,
    enum: EnumAssetsTypeField,
  })
  @IsEnum(EnumAssetsTypeField)
  @IsOptional()
  @Field(() => EnumAssetsTypeField, {
    nullable: true,
  })
  typeField?: "Option1" | null;

  @ApiProperty({
    required: false,
    enum: EnumAssetsStatus,
  })
  @IsEnum(EnumAssetsStatus)
  @IsOptional()
  @Field(() => EnumAssetsStatus, {
    nullable: true,
  })
  status?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: () => [Assignments],
  })
  @ValidateNested()
  @Type(() => Assignments)
  @IsOptional()
  assignmentsItems?: Array<Assignments>;

  @ApiProperty({
    required: false,
    type: () => Departments,
  })
  @ValidateNested()
  @Type(() => Departments)
  @IsOptional()
  department?: Departments | null;
}

export { Assets as Assets };
