/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsEnum,
  ValidateNested,
} from "class-validator";
import { EnumAssetsTypeField } from "./EnumAssetsTypeField";
import { EnumAssetsStatus } from "./EnumAssetsStatus";
import { AssignmentsUpdateManyWithoutAssetsItemsInput } from "./AssignmentsUpdateManyWithoutAssetsItemsInput";
import { Type } from "class-transformer";
import { DepartmentsWhereUniqueInput } from "../../departments/base/DepartmentsWhereUniqueInput";

@InputType()
class AssetsUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumAssetsTypeField,
  })
  @IsEnum(EnumAssetsTypeField)
  @IsOptional()
  @Field(() => EnumAssetsTypeField, {
    nullable: true,
  })
  typeField?: "Option1" | null;

  @ApiProperty({
    required: false,
    enum: EnumAssetsStatus,
  })
  @IsEnum(EnumAssetsStatus)
  @IsOptional()
  @Field(() => EnumAssetsStatus, {
    nullable: true,
  })
  status?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: () => AssignmentsUpdateManyWithoutAssetsItemsInput,
  })
  @ValidateNested()
  @Type(() => AssignmentsUpdateManyWithoutAssetsItemsInput)
  @IsOptional()
  @Field(() => AssignmentsUpdateManyWithoutAssetsItemsInput, {
    nullable: true,
  })
  assignmentsItems?: AssignmentsUpdateManyWithoutAssetsItemsInput;

  @ApiProperty({
    required: false,
    type: () => DepartmentsWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DepartmentsWhereUniqueInput)
  @IsOptional()
  @Field(() => DepartmentsWhereUniqueInput, {
    nullable: true,
  })
  department?: DepartmentsWhereUniqueInput | null;
}

export { AssetsUpdateInput as AssetsUpdateInput };
